### ISSUE TITLE
Error installing from Quicklisp

### ISSUE THREAD

**Issue by sebasmonia** [soemraws/cl-libusb#10]
This might be a problem of my environment, but my Lisp-fu is way too low to figure it out.

When I attempt to install cl-libusb using quicklisp, I get the following error:

```
Subprocess #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {100B5CE3A3}>
 with command ("gcc" "-o"
               "/home/hoagie/.cache/common-lisp/sbcl-2.0.1-5.fc34-linux-x64/home/hoagie/quicklisp/dists/quicklisp/software/cl-libusb-20210228-git/libusb-grovel__grovel-tmpGYUNPZCY.o"
               "-c" "-O2" "-fexceptions" "-g"
               "-grecord-gcc-switches" "-pipe" "-Wall"
               "-Werror=format-security"
               "-Wp,-D_FORTIFY_SOURCE=2"
               "-Wp,-D_GLIBCXX_ASSERTIONS"
               "-specs=/usr/lib/rpm/redhat/redhat-hardened-cc1"
               "-fstack-protector-strong"
               "-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1"
               "-m64" "-mtune=generic"
               "-fasynchronous-unwind-tables"
               "-fstack-clash-protection" "-fcf-protection"
               "-D_LARGEFILE_SOURCE" "-D_LARGEFILE64_SOURCE"
               "-D_FILE_OFFSET_BITS=64" "-Wunused-parameter"
               "-fno-omit-frame-pointer"
               "-momit-leaf-frame-pointer" "-fno-pie" "-fPIC"
               "-I/home/hoagie/quicklisp/dists/quicklisp/software/cffi_0.23.0/"
               "/home/hoagie/.cache/common-lisp/sbcl-2.0.1-5.fc34-linux-x64/home/hoagie/quicklisp/dists/quicklisp/software/cl-libusb-20210228-git/libusb-grovel__grovel.c")
 exited with error code 1
   [Condition of type CFFI-GROVEL:GROVEL-ERROR]
```

I think it is a problem compiling libusb. The library is installed in my system, though.
Had this happen in Fedora 33 and Fedora 34 (beta) in two different laptops.

Thank you!

**Comment by sebasmonia** [comment]
Apparently the file `libusb-grovel__grovel.cgf` is missing?

**Comment by j3pic** [comment]
I got a similar error on Debian, but then I installed `libusb-dev` and it loaded.

If you look in your `*inferior-lisp*` Emacs buffer, you'll see the error from your C compiler. On mine, it was:

    /home/redacted/.cache/common-lisp/sbcl-1.4.16.debian-linux-x64/home/redacted/quicklisp/dists/quicklisp/software/cl-libusb-20191227-git/libusb-grovel__grovel.c:6:10: fatal error: usb.h: No such file or directory
     #include <usb.h>
              ^~~~~~~
    compilation terminated.

**Comment by sebasmonia** [comment]
That was it, for Fedora the package is `libusb-devel`. Thank you for the tip on checking the inferior process!
